### ISSUE TITLE
[BUG] Rumble seemingly crashing the application during normal use

### ISSUE THREAD

**Issue by tenroseUK** [Davidobot/BetterJoyForCemu#1203]
**Describe the bug**
Rumble is seemingly crashing the application during normal use.

**Expected behavior**
Not to crash

**Controller (please complete the following information):**
Pro controller
Bluetooth

Windows event viewer shows the following unhandled exception during normal use. I'm playing Path of Exile 2 for what it's worth.

Application Error
Faulting application name: BetterJoyForCemu.exe, version: 1.0.0.0, time stamp: 0x619b7d9a
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00007ff97b326614
Faulting process ID: 0x0x6584
Faulting application start time: 0x0x1DB48F9205AFDDF
Faulting application path: C:\Installed Applications\BetterJoy\BetterJoyForCemu.exe
Faulting module path: unknown
Report ID: 9c443c68-10fa-4c17-9aac-8130990d144b
Faulting package full name: 
Faulting package-relative application ID: 

.NET Runtime
Application: BetterJoyForCemu.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at BetterJoyForCemu.Joycon+Rumble.GetData()
   at BetterJoyForCemu.Joycon.Poll()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by inhe8** [comment]
This fork fixed it for me: https://github.com/d3xMachina/BetterJoy/tree/v8.4.9
